'use client';
import {useEffect,useMemo,useState} from 'react';
import {CLUBS,createSeasonSchedule} from '../src/lib/baseball/league';
import {calculateStandings} from '../src/lib/baseball/standings';
import {createLeaguePlayers,lineupFor,type SimPlayer} from '../src/lib/baseball/players';
import {persistedRowsToSimPlayers} from '../src/lib/baseball/persistentPlayers';
import {simulateBoxScore,BoxScore} from '../src/lib/baseball/boxscore';
import {battingLeaders} from '../src/lib/baseball/stats';
import {rollDailyInjuries} from '../src/lib/baseball/injuries';
import {processDailyLeagueAI,type LeagueAIEvent} from '../src/lib/baseball/dailyLeagueAI';
import {interpretOfficeDirection,initialCharacter,reactToAction,characterDialogue} from '../src/lib/baseball/officeAI';
import {persistTrade} from '../src/lib/persistence/frontOffice';
import {executeOfficeAction} from '../src/lib/persistence/office';
import {listUniverses,loadUniverse,saveDay} from '../src/lib/persistence/universe';
import {createRealUniverse} from '../src/lib/mlb/seedUniverse';
import {currentUser,signInWithEmail,signOut} from '../src/lib/auth';
import type {SimGameResult} from '../src/lib/baseball/sim';
type Screen='home'|'auth'|'saves'|'teams'|'office'|'lineup'|'game'|'paper'|'box';
const dateForDay=(day:number)=>{const d=new Date('2027-04-01T12:00:00Z');d.setUTCDate(d.getUTCDate()+day-1);return d.toISOString().slice(0,10)};
export default function Home(){const schedule=useMemo(()=>createSeasonSchedule(),[]),demoPlayers=useMemo(()=>createLeaguePlayers(),[]);const[activePlayers,setActivePlayers]=useState<SimPlayer[]>(demoPlayers),[screen,setScreen]=useState<Screen>('home'),[teamId,setTeamId]=useState('bal'),[day,setDay]=useState(1),[boxes,setBoxes]=useState<BoxScore[]>([]),[today,setToday]=useState<BoxScore[]>([]),[direction,setDirection]=useState(''),[officeReply,setOfficeReply]=useState(''),[email,setEmail]=useState(''),[user,setUser]=useState<any>(null),[universeId,setUniverseId]=useState<string|null>(null),[saves,setSaves]=useState<any[]>([]),[status,setStatus]=useState(''),[injuries,setInjuries]=useState<any[]>([]),[leagueEvents,setLeagueEvents]=useState<LeagueAIEvent[]>([]);useEffect(()=>{currentUser().then(setUser).catch(()=>{})},[]);const team=CLUBS.find(t=>t.id===teamId)!;const resultRows:SimGameResult[]=boxes.map(b=>({gameId:b.gameId,awayId:b.awayId,homeId:b.homeId,awayRuns:b.awayRuns,homeRuns:b.homeRuns,innings:b.innings.length,headline:''}));const standings=calculateStandings(resultRows),row=standings.find(s=>s.teamId===teamId)!;const game=schedule.find(g=>g.day===day&&(g.awayId===teamId||g.homeId===teamId)),opp=game?CLUBS.find(c=>c.id===(game.awayId===teamId?game.homeId:game.awayId)):undefined;const lineup=lineupFor(teamId,activePlayers);const userBox=today.find(b=>b.awayId===teamId||b.homeId===teamId);
async function hydrateUniverse(id:string){const x=await loadUniverse(id);const real=persistedRowsToSimPlayers(x.players??[],x.teams??[]);if(real.length<200)throw new Error(`Universe player load incomplete: only ${real.length} active MLB players found`);setActivePlayers(real);return x}
async function newUniverse(){if(!user){setScreen('auth');return}setStatus('Importing real 2026 MLB 40-man rosters and building your 2027 universe…');try{const created=await createRealUniverse(teamId,2026,2027);setUniverseId(created.universe.id);await hydrateUniverse(created.universe.id);setBoxes([]);setDay(1);setStatus(`Universe created with ${created.playerCount} real MLB players · source snapshot ${new Date(created.snapshotAt).toLocaleString()}`);setScreen('office')}catch(e:any){setStatus(e.message)}}
async function openSaves(){if(!user){setScreen('auth');return}try{setSaves(await listUniverses());setScreen('saves')}catch(e:any){setStatus(e.message)}}
async function resume(id:string){setStatus('Loading real-player universe…');try{const x=await hydrateUniverse(id);setUniverseId(id);setTeamId(x.universe.user_team_key);const loaded=(x.games??[]).filter((g:any)=>g.box_score).map((g:any)=>g.box_score as BoxScore);setBoxes(loaded);const start=new Date('2027-04-01T12:00:00Z'),cur=new Date(`${x.universe.game_date}T12:00:00Z`);setDay(Math.max(1,Math.round((cur.getTime()-start.getTime())/86400000)+2));setStatus(`Loaded · ${x.players?.length??0} saved players · living league active`);setScreen('office')}catch(e:any){setStatus(e.message)}}
async function sendDirection(){if(!direction.trim()){setOfficeReply('Type a direction first.');return}if(!universeId){setOfficeReply('Start or resume a cloud universe before issuing persistent GM directions.');return}setStatus('Your staff is interpreting the instruction…');try{const actions=interpretOfficeDirection(direction,teamId,activePlayers);const replies:string[]=[];for(const action of actions){const p=action.playerId?activePlayers.find(x=>x.id===action.playerId):undefined;const state=p?reactToAction(initialCharacter(p),action):undefined;const result=await executeOfficeAction(universeId,teamId,action,state);replies.push(p&&state?`${result.message} ${characterDialogue(p,state,action)}`:result.message)}await hydrateUniverse(universeId);setOfficeReply(replies.join(' '));setStatus('Direction processed and universe updated.');setDirection('')}catch(e:any){setOfficeReply(`Staff could not execute that instruction: ${e.message}`);setStatus('Direction needs attention.')}}
async function playDay(){if(universeId&&activePlayers===demoPlayers){setStatus('Real-player roster is not loaded. Resume the universe before simulating.');return}const b=schedule.filter(g=>g.day===day).map(g=>simulateBoxScore(g,day,activePlayers,universeId??'guest'));const inj=rollDailyInjuries(activePlayers,day,universeId??'guest').filter(i=>activePlayers.find(p=>p.id===i.playerId)?.teamId===teamId);const all=[...boxes,...b];const ai=processDailyLeagueAI(activePlayers,all,day,teamId);setToday(b);setBoxes(all);setInjuries(inj);setLeagueEvents(ai.events);setScreen('paper');if(universeId){setStatus('Saving results and processing all 30 front offices…');try{await saveDay(universeId,2027,dateForDay(day),b);for(const trade of ai.trades)await persistTrade(universeId,trade);const refreshed=await hydrateUniverse(universeId);setStatus(`Saved · ${refreshed.players?.length??0} players · ${ai.decisions.length} AI front offices processed · ${ai.trades.length} autonomous trades`)}catch(e:any){setStatus(`Save failed: ${e.message}`)}}}
function advance(){setDay(x=>x+1);setToday([]);setInjuries([]);setLeagueEvents([]);setScreen('office')}
if(screen==='auth')return <main className="cover"><div className="kicker">SAVE YOUR BASEBALL WORLD</div><h1>SIGN IN</h1><p className="deck">Enter your email. Supabase will send a passwordless sign-in link.</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><button onClick={async()=>{try{await signInWithEmail(email);setStatus('Check your email for the sign-in link.')}catch(e:any){setStatus(e.message)}}}>EMAIL ME A SIGN-IN LINK →</button><p>{status}</p><button onClick={()=>setScreen('home')}>BACK</button></main>;
if(screen==='saves')return <main><header><b>BASEBALL UNIVERSE</b><span>CONTINUE</span></header><section className="paper"><h2>Your Universes</h2>{saves.length?saves.map(s=><button key={s.id} onClick={()=>resume(s.id)}>{s.name} · {s.game_date} · {s.current_season} →</button>):<p>No saved universes yet.</p>}<button onClick={()=>setScreen('home')}>BACK</button></section></main>;
if(screen==='home')return <main className="cover"><div className="kicker">AN AI BASEBALL WORLD</div><h1>BASEBALL<br/>UNIVERSE</h1><p className="deck">162 games. Thirty clubs. Every plate appearance creates history.</p><button onClick={()=>setScreen('teams')}>BEGIN A NEW UNIVERSE →</button><button onClick={openSaves}>CONTINUE UNIVERSE →</button>{user?<><p className="small">Signed in · persistent saves enabled</p><button onClick={async()=>{await signOut();setUser(null)}}>SIGN OUT</button></>:<button onClick={()=>setScreen('auth')}>SIGN IN FOR CLOUD SAVES</button>}<p>{status}</p></main>;
if(screen==='teams')return <main><header><b>BASEBALL UNIVERSE</b><span>NEW UNIVERSE / 2027</span></header><section className="paper"><div className="kicker">GM / MANAGER MODE · REAL MLB PLAYER SEED</div><h2>Choose Your Club</h2><p>Starting rosters are frozen from the latest 2026 MLB 40-man data available when you create the universe. After creation, your alternate baseball world becomes authoritative.</p><div className="teams">{CLUBS.map(t=><button className={teamId===t.id?'selected':''} key={t.id} onClick={()=>setTeamId(t.id)}>{t.city} {t.name}</button>)}</div><button className="primary" onClick={newUniverse}>IMPORT MLB & START — {team.abbr} →</button><p>{status}</p></section></main>;
if(screen==='lineup')return <main><header><b>BASEBALL UNIVERSE</b><span>LINEUP CARD</span></header><section className="paper"><div className="kicker">ACTIVE LINEUP · SAVED ROSTER</div><h2>{team.name}</h2>{lineup.map((p,i)=><p key={p.id}><b>{i+1}. {p.name}</b> — {p.position} · CON {p.contact} · POW {p.power} · FAT {p.fatigue??0}</p>)}<button className="primary" onClick={()=>setScreen('office')}>POST LINEUP →</button></section></main>;
if(screen==='game')return <main><header><b>BASEBALL UNIVERSE</b><span>DAY {day} / 162</span></header><section className="paper center"><div className="kicker">TODAY'S GAME</div><h2>{team.abbr}<br/><span className="vs">VS.</span><br/>{opp?.abbr??'TBD'}</h2><p>Every game today is simulated with the real players saved inside this universe. All other clubs make independent front-office decisions after the games.</p><button className="primary huge" onClick={playDay}>PLAY MLB DAY →</button></section></main>;
if(screen==='box'&&userBox){const away=CLUBS.find(c=>c.id===userBox.awayId)!,home=CLUBS.find(c=>c.id===userBox.homeId)!;return <main><header><b>OFFICIAL BOX SCORE</b><span>FINAL</span></header><section className="paper"><h2>{away.abbr} {userBox.awayRuns} — {home.abbr} {userBox.homeRuns}</h2><p>Hits: {away.abbr} {userBox.awayHits} · {home.abbr} {userBox.homeHits}</p><h3>Line Score</h3><p>{userBox.innings.map(i=>i.inning).join('  ')}</p><p>{away.abbr}: {userBox.innings.map(i=>i.away).join('  ')}</p><p>{home.abbr}: {userBox.innings.map(i=>i.home).join('  ')}</p><h3>{team.abbr} Batting</h3>{(userBox.awayId===teamId?userBox.awayBatting:userBox.homeBatting).map(l=>{const p=activePlayers.find(x=>x.id===l.playerId);return <p key={l.playerId}>{p?.name??'Unknown player'}: {l.h}-{l.ab}, {l.hr} HR, {l.rbi} RBI, {l.bb} BB</p>})}<button className="primary" onClick={()=>setScreen('paper')}>BACK TO BASEBALL TIMES →</button></section></main>}
if(screen==='paper'){const avg=battingLeaders(boxes,activePlayers,'AVG'),hrs=battingLeaders(boxes,activePlayers,'HR');return <main><header><b>THE BASEBALL TIMES</b><span>DAY {day} · FINAL EDITION</span></header><section className="paper"><div className="kicker">YOUR CLUB</div><h2>{userBox?`${CLUBS.find(c=>c.id===userBox.awayId)?.abbr} ${userBox.awayRuns} — ${CLUBS.find(c=>c.id===userBox.homeId)?.abbr} ${userBox.homeRuns}`:'OFF DAY'}</h2><p><b>{status}</b></p>{injuries.length>0&&<article><div className="kicker">MEDICAL / ACTION REQUIRED</div>{injuries.map(i=><p key={i.playerId}><b>{i.name}</b> — {i.severity.replaceAll('_',' ')} · estimated {i.days} days</p>)}</article>}{leagueEvents.length>0&&<article><div className="kicker">AROUND THE FRONT OFFICES</div>{leagueEvents.slice(0,8).map((e,i)=><p key={`${e.type}-${i}`}><b>{e.type}</b> — {e.headline}</p>)}</article>}{userBox&&<button onClick={()=>setScreen('box')}>READ OFFICIAL BOX SCORE →</button>}<div className="grid"><article><h3>Around the League</h3>{today.map(b=><p key={b.gameId}>{CLUBS.find(c=>c.id===b.awayId)?.abbr} {b.awayRuns} — {CLUBS.find(c=>c.id===b.homeId)?.abbr} {b.homeRuns}</p>)}</article><article><h3>League Leaders</h3><b>AVG</b>{avg.map(x=><p key={x.player.id}>{x.player.name} · {Number(x.value).toFixed(3).replace(/^0/,'')}</p>)}<b>HR</b>{hrs.map(x=><p key={x.player.id}>{x.player.name} · {x.value}</p>)}</article></div><button className="primary" onClick={advance}>ADVANCE TO TOMORROW →</button></section></main>}
return <main><header><b>BASEBALL UNIVERSE</b><span>{dateForDay(day)} · DAY {day}/162</span></header><section className="paper"><div className="mast"><div><div className="kicker">YOUR CLUB</div><h2>{team.city} {team.name}</h2><p className="record">{row.w}–{row.l} · {team.league} {team.division}</p><p className="small">{universeId?`REAL-PLAYER CLOUD UNIVERSE · ${activePlayers.length} ACTIVE MLB PLAYERS · LIVING LEAGUE ON`:'LOCAL DEMO'}</p></div><div className="stamp">GM +<br/>MANAGER</div></div><div className="grid"><article><div className="kicker">TODAY</div><h3>{opp?`${team.abbr} vs. ${opp.abbr}`:'Off day'}</h3><button onClick={()=>setScreen('lineup')}>SET LINEUP →</button><button className="primary" onClick={()=>setScreen('game')}>GO TO GAME DAY →</button></article><article><div className="kicker">IN YOUR OFFICE</div><h3>Give your staff direction.</h3><textarea value={direction} onChange={e=>setDirection(e.target.value)} placeholder="Put Adley Rutschman on the 10-day IL. Rest Gunnar tomorrow. Call up our Triple-A catcher…"/><button onClick={sendDirection}>SEND DIRECTION</button>{officeReply&&<div><div className="kicker">STAFF / PLAYER RESPONSE</div><p>{officeReply}</p></div>}</article></div><p>{status}</p></section></main>}
