'use client';

import { useMemo, useState } from 'react';
import { CLUBS, createSeasonSchedule } from '../src/lib/baseball/league';
import { simulateDay, SimGameResult } from '../src/lib/baseball/sim';
import { calculateStandings } from '../src/lib/baseball/standings';
import { BALTIMORE_DEMO_ROSTER, defaultLineup } from '../src/lib/baseball/rosters';

type Screen='home'|'teams'|'office'|'lineup'|'game'|'paper';

export default function Home(){
 const schedule=useMemo(()=>createSeasonSchedule(),[]); const [screen,setScreen]=useState<Screen>('home'); const [teamId,setTeamId]=useState('bal'); const [day,setDay]=useState(1); const [results,setResults]=useState<SimGameResult[]>([]); const [today,setToday]=useState<SimGameResult[]>([]); const [direction,setDirection]=useState('');
 const team=CLUBS.find(t=>t.id===teamId)!; const standings=calculateStandings(results); const row=standings.find(s=>s.teamId===teamId)!; const todaysGame=schedule.find(g=>g.day===day&&(g.awayId===teamId||g.homeId===teamId)); const opponent=todaysGame?CLUBS.find(c=>c.id===(todaysGame.awayId===teamId?todaysGame.homeId:todaysGame.awayId)):undefined; const lineup=defaultLineup(BALTIMORE_DEMO_ROSTER);
 function playDay(){const r=simulateDay(schedule,day,'universe-2027-001');setToday(r);setResults(prev=>[...prev,...r]);setScreen('paper')}
 function advance(){setDay(d=>d+1);setToday([]);setScreen('office')}
 if(screen==='home')return <main className="cover"><div className="kicker">AN AI BASEBALL WORLD</div><h1>BASEBALL<br/>UNIVERSE</h1><p className="deck">162 games. Thirty clubs. One living baseball world that remembers what you do.</p><button onClick={()=>setScreen('teams')}>BEGIN A NEW UNIVERSE →</button><div className="rule"/><p className="small">The simulation owns baseball truth. AI makes the people, news and consequences come alive.</p></main>;
 if(screen==='teams')return <main><header><b>BASEBALL UNIVERSE</b><span>NEW UNIVERSE / 2027</span></header><section className="paper"><div className="kicker">GM / MANAGER MODE</div><h2>Choose Your Club</h2><p>All 30 organizations will continue playing, trading and evolving around you.</p><div className="teams">{CLUBS.map(t=><button className={teamId===t.id?'selected':''} key={t.id} onClick={()=>setTeamId(t.id)}>{t.city} {t.name}</button>)}</div><button className="primary" onClick={()=>setScreen('office')}>START UNIVERSE — {team.abbr} →</button></section></main>;
 if(screen==='lineup')return <main><header><b>BASEBALL UNIVERSE</b><span>LINEUP CARD</span></header><section className="paper"><div className="kicker">DEMO ROSTER / IMPORT LAYER NEXT</div><h2>Opening Lineup</h2>{teamId==='bal'?lineup.map(slot=>{const p=BALTIMORE_DEMO_ROSTER.find(x=>x.id===slot.playerId)!;return <p key={p.id}><b>{slot.order}. {p.name}</b> — {slot.position}</p>}):<p>The roster importer will populate this club from the frozen Opening Day snapshot.</p>}<button className="primary" onClick={()=>setScreen('office')}>POST LINEUP →</button></section></main>;
 if(screen==='game')return <main><header><b>BASEBALL UNIVERSE</b><span>DAY {day} / 162</span></header><section className="paper center"><div className="kicker">TODAY'S GAME</div><h2>{team.abbr}<br/><span className="vs">VS.</span><br/>{opponent?.abbr??'TBD'}</h2><p>Playing this game processes the complete 30-team league slate. Results are seeded and deterministic rather than chosen by AI.</p><button className="primary huge" onClick={playDay}>SIMULATE MLB DAY →</button></section></main>;
 if(screen==='paper'){const userGame=today.find(g=>g.awayId===teamId||g.homeId===teamId);const userWon=userGame?((userGame.awayId===teamId&&userGame.awayRuns>userGame.homeRuns)||(userGame.homeId===teamId&&userGame.homeRuns>userGame.awayRuns)):false;return <main><header><b>THE BASEBALL TIMES</b><span>DAY {day} · FINAL EDITION</span></header><section className="paper"><div className="kicker">YOUR CLUB</div><h2>{userGame?.headline??'OFF DAY'}</h2><div className="headline"><h1>{userWon?'VICTORY CHANGES THE MOOD':'THE SEASON MOVES FORWARD'}</h1><p>The official score below came from the deterministic league engine. The AI narrative layer will receive these verified facts and may describe them, but never rewrite them.</p></div><div className="grid"><article><h3>Around the League</h3>{today.map(g=>{const a=CLUBS.find(c=>c.id===g.awayId)!,h=CLUBS.find(c=>c.id===g.homeId)!;return <p key={g.gameId}>{a.abbr} {g.awayRuns} — {h.abbr} {g.homeRuns}{g.innings>9?` (${g.innings})`:''}</p>})}</article><article><h3>Standings Snapshot</h3>{calculateStandings([...results]).slice(0,10).map(s=><p key={s.teamId}>{CLUBS.find(c=>c.id===s.teamId)?.abbr} <b>{s.w}–{s.l}</b> · {s.pct.toFixed(3).replace(/^0/,'')}</p>)}</article></div><button className="primary" onClick={advance}>ADVANCE TO TOMORROW →</button></section></main>}
 return <main><header><b>BASEBALL UNIVERSE</b><span>APRIL {day+1}, 2027 · DAY {day}/162</span></header><section className="paper"><div className="mast"><div><div className="kicker">YOUR CLUB</div><h2>{team.city} {team.name}</h2><p className="record">{row.w}–{row.l} · {team.league} {team.division}</p></div><div className="stamp">GM +<br/>MANAGER</div></div><div className="grid"><article><div className="kicker">TODAY</div><h3>{opponent?`${team.abbr} vs. ${opponent.abbr}`:'Scheduled off day'}</h3><p>Day {day} of the 162-game universe.</p><button onClick={()=>setScreen('lineup')}>SET LINEUP →</button><button className="primary" onClick={()=>setScreen('game')}>GO TO GAME DAY →</button></article><article><div className="kicker">IN YOUR OFFICE</div><h3>Your manager is waiting.</h3><p>Give instructions naturally. The action interpreter/validator is now separated from authoritative game state so free-text AI cannot invent transactions or statistics.</p><textarea value={direction} onChange={e=>setDirection(e.target.value)} placeholder="Example: Rest our catcher today and call up the Triple-A catcher…"/><button onClick={()=>alert(direction?'Direction captured for the structured AI action layer.':'Type a direction first.')}>SEND DIRECTION</button></article></div><div className="headline"><div className="kicker">THE WORLD IS ACTIVE</div><h2>ALL 30 CLUBS PLAY ON</h2><p>Every simulated date now processes a full league slate and rebuilds standings from authoritative results. Rosters, box-score detail, injuries, events and the persistent database plug into this same world model next.</p></div></section></main>;
}
