'use client';
import {useEffect,useMemo,useState} from 'react';
import {CLUBS,createSeasonSchedule} from '../src/lib/baseball/league';
import {calculateStandings} from '../src/lib/baseball/standings';
import {createLeaguePlayers,type SimPlayer} from '../src/lib/baseball/players';
import {persistedRowsToSimPlayers} from '../src/lib/baseball/persistentPlayers';
import {simulateBoxScore,BoxScore} from '../src/lib/baseball/boxscore';
import {battingLeaders} from '../src/lib/baseball/stats';
import {rollDailyInjuries} from '../src/lib/baseball/injuries';
import {processDailyLeagueAI,type LeagueAIEvent} from '../src/lib/baseball/dailyLeagueAI';
import {interpretOfficeDirection,initialCharacter,reactToAction,characterDialogue} from '../src/lib/baseball/officeAI';
import {persistTrade} from '../src/lib/persistence/frontOffice';
import {executeOfficeAction} from '../src/lib/persistence/office';
import {listUniverses,loadUniverse,saveDay} from '../src/lib/persistence/universe';
import {createRealUniverse} from '../src/lib/mlb/seedUniverse';
import {currentUser,signInWithEmail,signOut} from '../src/lib/auth';
import type {SimGameResult} from '../src/lib/baseball/sim';
type Screen='home'|'auth'|'saves'|'teams'|'office'|'game'|'paper'|'box';
const dateForDay=(day:number)=>{const d=new Date('2027-04-01T12:00:00Z');d.setUTCDate(d.getUTCDate()+day-1);return d.toISOString().slice(0,10)};
export default function Home(){const schedule=useMemo(()=>createSeasonSchedule(),[]),demoPlayers=useMemo(()=>createLeaguePlayers(),[]);const[activePlayers,setActivePlayers]=useState<SimPlayer[]>(demoPlayers),[screen,setScreen]=useState<Screen>('home'),[teamId,setTeamId]=useState('bal'),[day,setDay]=useState(1),[boxes,setBoxes]=useState<BoxScore[]>([]),[today,setToday]=useState<BoxScore[]>([]),[direction,setDirection]=useState(''),[officeReply,setOfficeReply]=useState(''),[email,setEmail]=useState(''),[user,setUser]=useState<any>(null),[universeId,setUniverseId]=useState<string|null>(null),[saves,setSaves]=useState<any[]>([]),[status,setStatus]=useState(''),[injuries,setInjuries]=useState<any[]>([]),[leagueEvents,setLeagueEvents]=useState<LeagueAIEvent[]>([]);useEffect(()=>{currentUser().then(setUser).catch(()=>{})},[]);const team=CLUBS.find(t=>t.id===teamId)!;const resultRows:SimGameResult[]=boxes.map(b=>({gameId:b.gameId,awayId:b.awayId,homeId:b.homeId,awayRuns:b.awayRuns,homeRuns:b.homeRuns,innings:b.innings.length,headline:''}));const standings=calculateStandings(resultRows),row=standings.find(s=>s.teamId===teamId)!;const game=schedule.find(g=>g.day===day&&(g.awayId===teamId||g.homeId===teamId)),opp=game?CLUBS.find(c=>c.id===(game.awayId===teamId?game.homeId:game.awayId)):undefined;const userBox=today.find(b=>b.awayId===teamId||b.homeId===teamId);
async function hydrateUniverse(id:string){const x=await loadUniverse(id);const real=persistedRowsToSimPlayers(x.players??[],x.teams??[]);if(real.length<200)throw new Error(`Universe player load incomplete: only ${real.length} active MLB players found`);setActivePlayers(real);return x}
async function newUniverse(){if(!user){setScreen('auth');return}setStatus('Importing real 2026 MLB 40-man rosters and building your 2027 universe…');try{const created=await createRealUniverse(teamId,2026,2027);setUniverseId(created.universe.id);await hydrateUniverse(created.universe.id);setBoxes([]);setDay(1);setStatus(`Universe created with ${created.playerCount} real MLB players`);setScreen('office')}catch(e:any){setStatus(e.message)}}
async function openSaves(){if(!user){setScreen('auth');return}try{setSaves(await listUniverses());setScreen('saves')}catch(e:any){setStatus(e.message)}}
async function resume(id:string){try{const x=await hydrateUniverse(id);setUniverseId(id);setTeamId(x.universe.user_team_key);setBoxes((x.games??[]).filter((g:any)=>g.box_score).map((g:any)=>g.box_score));const start=new Date('2027-04-01T12:00:00Z'),cur=new Date(`${x.universe.game_date}T12:00:00Z`);setDay(Math.max(1,Math.round((cur.getTime()-start.getTime())/86400000)+2));setScreen('office')}catch(e:any){setStatus(e.message)}}
async function sendDirection(){if(!direction.trim()||!universeId)return;try{const actions=interpretOfficeDirection(direction,teamId,activePlayers);const replies:string[]=[];for(const action of actions){const p=action.playerId?activePlayers.find(x=>x.id===action.playerId):undefined;const state=p?reactToAction(initialCharacter(p),action):undefined;const result=await executeOfficeAction(universeId,teamId,action,state);replies.push(p&&state?`${result.message} ${characterDialogue(p,state,action)}`:result.message)}await hydrateUniverse(universeId);setOfficeReply(replies.join(' '));setDirection('')}catch(e:any){setOfficeReply(e.message)}}
async function playDay(){const b=schedule.filter(g=>g.day===day).map(g=>simulateBoxScore(g,day,activePlayers,universeId??'guest'));const inj=rollDailyInjuries(activePlayers,day,universeId??'guest').filter(i=>activePlayers.find(p=>p.id===i.playerId)?.teamId===teamId);const all=[...boxes,...b];const ai=processDailyLeagueAI(activePlayers,all,day,teamId);setToday(b);setBoxes(all);setInjuries(inj);setLeagueEvents(ai.events);setScreen('paper');if(universeId){try{await saveDay(universeId,2027,dateForDay(day),b);for(const trade of ai.trades)await persistTrade(universeId,trade);await hydrateUniverse(universeId)}catch(e:any){setStatus(e.message)}}}
function advance(){setDay(x=>x+1);setToday([]);setInjuries([]);setLeagueEvents([]);setScreen('office')}
if(screen==='auth')return <main className="cover"><h1>SIGN IN</h1><input value={email} onChange={e=>setEmail(e.target.value)}/><button onClick={async()=>{await signInWithEmail(email)}}>EMAIL SIGN-IN LINK</button><button onClick={()=>setScreen('home')}>BACK</button></main>;
if(screen==='saves')return <main><header><b>BASEBALL UNIVERSE</b><span>CONTINUE</span></header><section className="paper">{saves.map(s=><button key={s.id} onClick={()=>resume(s.id)}>{s.name} · {s.game_date} →</button>)}</section></main>;
if(screen==='home')return <main className="cover"><div className="kicker">AN AI BASEBALL WORLD</div><h1>BASEBALL<br/>UNIVERSE</h1><p className="deck">162 games. Thirty clubs. Every day is a baseball decision.</p><button onClick={()=>setScreen('teams')}>BEGIN A NEW UNIVERSE →</button><button onClick={openSaves}>CONTINUE UNIVERSE →</button>{user?<button onClick={async()=>{await signOut();setUser(null)}}>SIGN OUT</button>:<button onClick={()=>setScreen('auth')}>SIGN IN</button>}</main>;
if(screen==='teams')return <main><header><b>BASEBALL UNIVERSE</b><span>NEW UNIVERSE</span></header><section className="paper"><h2>Choose Your Club</h2><div className="teams">{CLUBS.map(t=><button key={t.id} onClick={()=>setTeamId(t.id)}>{t.city} {t.name}</button>)}</div><button className="primary" onClick={newUniverse}>IMPORT MLB & START →</button><p>{status}</p></section></main>;
if(screen==='game')return <main><header><b>BASEBALL UNIVERSE</b><span>DAY {day}</span></header><section className="paper center"><h2>{team.abbr} VS. {opp?.abbr??'TBD'}</h2><a className="primary huge" href="/game-day">SET LINEUP & GAME PLAN →</a><p>When your card is ready, return here to play the MLB day.</p><button className="primary" onClick={playDay}>PLAY MLB DAY →</button></section></main>;
if(screen==='box'&&userBox)return <main><header><b>OFFICIAL BOX SCORE</b><span>FINAL</span></header><section className="paper"><h2>{userBox.awayRuns} — {userBox.homeRuns}</h2><button onClick={()=>setScreen('paper')}>BACK</button></section></main>;
if(screen==='paper'){const avg=battingLeaders(boxes,activePlayers,'AVG');return <main><header><b>THE BASEBALL TIMES</b><span>DAY {day}</span></header><section className="paper"><h2>{userBox?`${userBox.awayRuns} — ${userBox.homeRuns}`:'OFF DAY'}</h2>{injuries.map(i=><p key={i.playerId}><b>{i.name}</b> — {i.severity}</p>)}{leagueEvents.slice(0,8).map((e,i)=><p key={i}><b>{e.type}</b> — {e.headline}</p>)}{avg.slice(0,5).map(x=><p key={x.player.id}>{x.player.name} · {Number(x.value).toFixed(3)}</p>)}<button className="primary" onClick={advance}>ADVANCE TO TOMORROW →</button></section></main>}
return <main><header><b>BASEBALL UNIVERSE</b><span>{dateForDay(day)}</span></header><section className="paper"><div className="kicker">MANAGER'S OFFICE</div><h2>{team.city} {team.name} · {row?.wins??0}-{row?.losses??0}</h2><p>{game?`Today: ${game.awayId===teamId?'at':'vs'} ${opp?.name}`:'Off day'}</p><a className="primary huge" href="/game-day">OPEN GAME DAY — SET TODAY'S CLUB →</a><button onClick={()=>setScreen('game')}>GO TO BALLPARK →</button><a href="/trade">TRADE DESK →</a><h3>In Your Office</h3><textarea value={direction} onChange={e=>setDirection(e.target.value)} placeholder="Give your staff a baseball instruction…"/><button onClick={sendDirection}>SEND DIRECTION →</button><p>{officeReply}</p><p>{status}</p></section></main>}
