import type { ScheduledGame } from './league';
import type { SimPlayer } from './players';
import { lineupFor, starterFor } from './players';

export type PAResult='OUT'|'BB'|'1B'|'2B'|'3B'|'HR';
export interface BattingLine { playerId:string; ab:number; r:number; h:number; doubles:number; triples:number; hr:number; rbi:number; bb:number }
export interface PitchingLine { playerId:string; outs:number; h:number; r:number; er:number; bb:number; hr:number }
export interface InningLine { inning:number; away:number; home:number }
export interface BoxScore { gameId:string; awayId:string; homeId:string; innings:InningLine[]; awayRuns:number; homeRuns:number; awayHits:number; homeHits:number; awayBatting:BattingLine[]; homeBatting:BattingLine[]; awayPitching:PitchingLine[]; homePitching:PitchingLine[]; keyPlays:string[] }
function hash(s:string){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}function rand(seed:string){let x=hash(seed)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function emptyBat(id:string):BattingLine{return{playerId:id,ab:0,r:0,h:0,doubles:0,triples:0,hr:0,rbi:0,bb:0}}
function pa(b:SimPlayer,p:SimPlayer,r:()=>number):PAResult{const skill=(b.contact*.45+b.power*.25+b.discipline*.3)-(p.pitching*.55+p.control*.25);const walk=Math.max(.055,Math.min(.13,.085+(b.discipline-p.control)*.001));const hit=Math.max(.19,Math.min(.36,.245+skill*.0015));const x=r();if(x<walk)return'BB';if(x>walk+hit)return'OUT';const power=Math.max(.06,Math.min(.25,.10+(b.power-65)*.003));const y=r();if(y<power)return'HR';if(y<power+.20)return'2B';if(y<power+.225)return'3B';return'1B'}
function half(lineup:SimPlayer[],pitcher:SimPlayer,r:()=>number,start:number){let outs=0,runs=0,hits=0,index=start;const bats=new Map(lineup.map(x=>[x.id,emptyBat(x.id)]));const bases:Array<SimPlayer|null>=[null,null,null];const key:string[]=[];while(outs<3){const b=lineup[index%9];index++;const l=bats.get(b.id)!;const result=pa(b,pitcher,r);if(result==='OUT'){l.ab++;outs++;continue}if(result==='BB'){l.bb++;if(bases[0]&&bases[1]&&bases[2]){runs++;l.rbi++;bases[2]!.id&&bats.get(bases[2]!.id)!.r++}if(bases[0]&&bases[1])bases[2]=bases[1];if(bases[0])bases[1]=bases[0];bases[0]=b;continue}l.ab++;l.h++;hits++;const n=result==='1B'?1:result==='2B'?2:result==='3B'?3:4;if(n===2)l.doubles++;if(n===3)l.triples++;if(n===4)l.hr++;let scored=0;for(let base=2;base>=0;base--){const runner=bases[base];if(!runner)continue;if(base+n>=3){runs++;scored++;bats.get(runner.id)!.r++;bases[base]=null}else{bases[base+n]=runner;bases[base]=null}}if(n===4){runs++;scored++;l.r++}else bases[n-1]=b;l.rbi+=scored;if(result==='HR')key.push(`${b.name} homered`)}return{runs,hits,next:index%9,bats,key}}
export function simulateBoxScore(game:ScheduledGame,day:number,players:SimPlayer[],universeSeed='universe'):BoxScore{const away=lineupFor(game.awayId,players),home=lineupFor(game.homeId,players),ap=starterFor(game.awayId,day,players),hp=starterFor(game.homeId,day,players),r=rand(`${universeSeed}:${game.id}:box`);let ai=0,hi=0,ar=0,hr=0,ah=0,hh=0,inning=1;const innings:InningLine[]=[],ab=new Map<string,BattingLine>(),hb=new Map<string,BattingLine>(),keys:string[]=[];while(inning<=9||ar===hr){const top=half(away,hp,r,ai);ai=top.next;ar+=top.runs;ah+=top.hits;top.bats.forEach((v,k)=>{const x=ab.get(k)||emptyBat(k);Object.keys(v).forEach(key=>{if(key!=='playerId')(x as any)[key]+=(v as any)[key]});ab.set(k,x)});const bot=half(home,ap,r,hi);hi=bot.next;hr+=bot.runs;hh+=bot.hits;bot.bats.forEach((v,k)=>{const x=hb.get(k)||emptyBat(k);Object.keys(v).forEach(key=>{if(key!=='playerId')(x as any)[key]+=(v as any)[key]});hb.set(k,x)});innings.push({inning,away:top.runs,home:bot.runs});keys.push(...top.key,...bot.key);inning++;if(inning>15&&ar===hr)hr++}return{gameId:game.id,awayId:game.awayId,homeId:game.homeId,innings,awayRuns:ar,homeRuns:hr,awayHits:ah,homeHits:hh,awayBatting:[...ab.values()],homeBatting:[...hb.values()],awayPitching:[{playerId:ap.id,outs:(innings.length)*3,h:hh,r:hr,er:hr,bb:0,hr:0}],homePitching:[{playerId:hp.id,outs:(innings.length)*3,h:ah,r:ar,er:ar,bb:0,hr:0}],keyPlays:keys.slice(0,8)}}
