import type {SimPlayer} from './players';
export type ClubPlan='CONTEND'|'HOLD'|'SELL';
export interface TeamStanding{teamId:string;w:number;l:number}
export interface FrontOfficeDecision{teamId:string;plan:ClubPlan;needs:string[];actions:Array<{type:'REST'|'IL_REPLACE'|'ROTATION'|'TRADE_BLOCK';playerId?:string;position?:string;reason:string}>}
export interface TradeProposal{fromTeamId:string;toTeamId:string;offeredPlayerId:string;requestedPlayerId:string;score:number;reason:string}
const pitchers=new Set(['P','SP','RP','CP']);
const overall=(p:SimPlayer)=>pitchers.has(p.position)?p.pitching*.45+p.control*.3+p.stamina*.15+p.health!*.05+(100-(p.fatigue??0))*.05:p.contact*.25+p.power*.22+p.discipline*.15+p.defense*.18+p.speed*.1+(p.health??100)*.05+(100-(p.fatigue??0))*.05;
export function clubPlan(s?:TeamStanding,day=1):ClubPlan{if(!s||day<70)return'HOLD';const pct=s.w/Math.max(1,s.w+s.l);if(pct>=.54)return'CONTEND';if(pct<=.46)return'SELL';return'HOLD'}
export function analyzeClub(teamId:string,players:SimPlayer[],standing?:TeamStanding,day=1):FrontOfficeDecision{const roster=players.filter(p=>p.teamId===teamId);const plan=clubPlan(standing,day),actions:FrontOfficeDecision['actions']=[],needs:string[]=[];for(const p of roster){if((p.health??100)<=30)actions.push({type:'IL_REPLACE',playerId:p.id,position:p.position,reason:`${p.name} is unavailable`});else if((p.fatigue??0)>=75)actions.push({type:'REST',playerId:p.id,position:p.position,reason:`${p.name} is heavily fatigued`})}const healthy=roster.filter(p=>(p.health??100)>30);if(healthy.filter(p=>pitchers.has(p.position)).length<10)needs.push('P');if(healthy.filter(p=>!pitchers.has(p.position)).length<12)needs.push('BAT');if(plan==='SELL')roster.filter(p=>overall(p)>=72).sort((a,b)=>overall(b)-overall(a)).slice(0,2).forEach(p=>actions.push({type:'TRADE_BLOCK',playerId:p.id,position:p.position,reason:'Club is selling and will listen on veterans'}));return{teamId,plan,needs,actions}}
export function generateTradeMarket(players:SimPlayer[],standings:TeamStanding[],day:number,userTeamId:string):TradeProposal[]{if(day<85||day>123)return[];const teams=Array.from(new Set(players.map(p=>p.teamId))),plans=Object.fromEntries(teams.map(t=>[t,analyzeClub(t,players,standings.find(s=>s.teamId===t),day)]));const sellers=teams.filter(t=>plans[t].plan==='SELL'),buyers=teams.filter(t=>plans[t].plan==='CONTEND'),proposals:TradeProposal[]=[];for(const buyer of buyers){for(const seller of sellers){if(buyer===seller)continue;const targets=players.filter(p=>p.teamId===seller&&(p.health??100)>50).sort((a,b)=>overall(b)-overall(a));const chips=players.filter(p=>p.teamId===buyer&&(p.health??100)>50).sort((a,b)=>overall(a)-overall(b));const target=targets[0],chip=chips.find(p=>overall(p)>=Math.max(45,overall(target??({} as SimPlayer))*.62));if(target&&chip){const gap=Math.abs(overall(target)-overall(chip));if(gap<35)proposals.push({fromTeamId:buyer,toTeamId:seller,offeredPlayerId:chip.id,requestedPlayerId:target.id,score:Math.round(100-gap),reason:`${buyer} is buying while ${seller} is selling`})}}}return proposals.filter((p,i,a)=>a.findIndex(x=>x.requestedPlayerId===p.requestedPlayerId)===i).filter(p=>p.fromTeamId!==userTeamId&&p.toTeamId!==userTeamId).slice(0,4)}
export function executeTrade(players:SimPlayer[],trade:TradeProposal):SimPlayer[]{return players.map(p=>p.id===trade.offeredPlayerId?{...p,teamId:trade.toTeamId}:p.id===trade.requestedPlayerId?{...p,teamId:trade.fromTeamId}:p)}
