import type { SimPlayer } from './players';
export interface PlayerHealth { playerId:string; fatigue:number; injuryRisk:number; injured:boolean; injury?:{type:string;daysRemaining:number;severity:'DAY_TO_DAY'|'IL10'|'IL60'} }
export interface BullpenState { teamId:string; pitchers:Array<{playerId:string;fatigue:number;available:boolean;lastUsedDay?:number}> }
function hash(s:string){let h=0;for(const c of s)h=(Math.imul(h,33)+c.charCodeAt(0))>>>0;return h}
export function initialHealth(players:SimPlayer[]):Record<string,PlayerHealth>{return Object.fromEntries(players.map(p=>[p.id,{playerId:p.id,fatigue:0,injuryRisk:2,injured:false}]))}
export function recoverHealth(health:Record<string,PlayerHealth>){const out:Record<string,PlayerHealth>={};for(const [id,h] of Object.entries(health)){const injury=h.injury?{...h.injury,daysRemaining:Math.max(0,h.injury.daysRemaining-1)}:undefined;out[id]={...h,fatigue:Math.max(0,h.fatigue-22),injury:injury?.daysRemaining?injury:undefined,injured:!!injury?.daysRemaining}}return out}
export function applyPitchingWorkload(health:Record<string,PlayerHealth>,playerId:string,pitches:number){const h=health[playerId]||{playerId,fatigue:0,injuryRisk:2,injured:false};return{...health,[playerId]:{...h,fatigue:Math.min(100,h.fatigue+Math.round(pitches*.55)),injuryRisk:Math.min(30,h.injuryRisk+pitches/80)}}}
export function maybeInjure(health:Record<string,PlayerHealth>,playerId:string,day:number,seed:string){const h=health[playerId];if(!h||h.injured)return health;const roll=(hash(`${seed}:${day}:${playerId}:injury`)%10000)/100;const threshold=.08+h.injuryRisk*.025+h.fatigue*.004;if(roll>=threshold)return health;const severe=(hash(`${seed}:${day}:${playerId}:severity`)%100)<12;const days=severe?60:10+(hash(`${seed}:${playerId}:days`)%12);return{...health,[playerId]:{...h,injured:true,injury:{type:playerId.includes('p')?'arm soreness':'soft tissue strain',daysRemaining:days,severity:severe?'IL60':'IL10'}}}}
export function bullpenFor(teamId:string,players:SimPlayer[],health:Record<string,PlayerHealth>,day:number):BullpenState{return{teamId,pitchers:players.filter(p=>p.teamId===teamId&&p.position==='RP').map(p=>({playerId:p.id,fatigue:health[p.id]?.fatigue||0,available:!(health[p.id]?.injured)&&((health[p.id]?.fatigue||0)<72),lastUsedDay:undefined}))}}
