export type League = 'AL' | 'NL';
export type Division = 'EAST' | 'CENTRAL' | 'WEST';

export interface ClubSeed { id:string; city:string; name:string; abbr:string; league:League; division:Division; strength:number }

export const CLUBS: ClubSeed[] = [
{id:'ari',city:'Arizona',name:'Diamondbacks',abbr:'ARI',league:'NL',division:'WEST',strength:76},{id:'atl',city:'Atlanta',name:'Braves',abbr:'ATL',league:'NL',division:'EAST',strength:82},{id:'bal',city:'Baltimore',name:'Orioles',abbr:'BAL',league:'AL',division:'EAST',strength:82},{id:'bos',city:'Boston',name:'Red Sox',abbr:'BOS',league:'AL',division:'EAST',strength:78},{id:'cws',city:'Chicago',name:'White Sox',abbr:'CWS',league:'AL',division:'CENTRAL',strength:68},{id:'chc',city:'Chicago',name:'Cubs',abbr:'CHC',league:'NL',division:'CENTRAL',strength:78},{id:'cin',city:'Cincinnati',name:'Reds',abbr:'CIN',league:'NL',division:'CENTRAL',strength:77},{id:'cle',city:'Cleveland',name:'Guardians',abbr:'CLE',league:'AL',division:'CENTRAL',strength:80},{id:'col',city:'Colorado',name:'Rockies',abbr:'COL',league:'NL',division:'WEST',strength:67},{id:'det',city:'Detroit',name:'Tigers',abbr:'DET',league:'AL',division:'CENTRAL',strength:79},{id:'hou',city:'Houston',name:'Astros',abbr:'HOU',league:'AL',division:'WEST',strength:80},{id:'kc',city:'Kansas City',name:'Royals',abbr:'KC',league:'AL',division:'CENTRAL',strength:78},{id:'laa',city:'Los Angeles',name:'Angels',abbr:'LAA',league:'AL',division:'WEST',strength:72},{id:'lad',city:'Los Angeles',name:'Dodgers',abbr:'LAD',league:'NL',division:'WEST',strength:90},{id:'mia',city:'Miami',name:'Marlins',abbr:'MIA',league:'NL',division:'EAST',strength:69},{id:'mil',city:'Milwaukee',name:'Brewers',abbr:'MIL',league:'NL',division:'CENTRAL',strength:80},{id:'min',city:'Minnesota',name:'Twins',abbr:'MIN',league:'AL',division:'CENTRAL',strength:76},{id:'nyy',city:'New York',name:'Yankees',abbr:'NYY',league:'AL',division:'EAST',strength:86},{id:'nym',city:'New York',name:'Mets',abbr:'NYM',league:'NL',division:'EAST',strength:84},{id:'ath',city:'Athletics',name:'Athletics',abbr:'ATH',league:'AL',division:'WEST',strength:72},{id:'phi',city:'Philadelphia',name:'Phillies',abbr:'PHI',league:'NL',division:'EAST',strength:85},{id:'pit',city:'Pittsburgh',name:'Pirates',abbr:'PIT',league:'NL',division:'CENTRAL',strength:72},{id:'sd',city:'San Diego',name:'Padres',abbr:'SD',league:'NL',division:'WEST',strength:83},{id:'sf',city:'San Francisco',name:'Giants',abbr:'SF',league:'NL',division:'WEST',strength:76},{id:'sea',city:'Seattle',name:'Mariners',abbr:'SEA',league:'AL',division:'WEST',strength:81},{id:'stl',city:'St. Louis',name:'Cardinals',abbr:'STL',league:'NL',division:'CENTRAL',strength:76},{id:'tb',city:'Tampa Bay',name:'Rays',abbr:'TB',league:'AL',division:'EAST',strength:75},{id:'tex',city:'Texas',name:'Rangers',abbr:'TEX',league:'AL',division:'WEST',strength:79},{id:'tor',city:'Toronto',name:'Blue Jays',abbr:'TOR',league:'AL',division:'EAST',strength:78},{id:'was',city:'Washington',name:'Nationals',abbr:'WSH',league:'NL',division:'EAST',strength:71}];

export interface ScheduledGame { id:string; day:number; awayId:string; homeId:string }

// Balanced 30-team round-robin scaffold. It creates a complete daily league slate and
// repeats rotating rounds until each club has 162 games. Later the MLB importer can
// replace this schedule without changing the simulation interfaces.
export function createSeasonSchedule(): ScheduledGame[] {
  const ids = CLUBS.map(c=>c.id); const rounds: Array<Array<[string,string]>>=[]; let rotation=[...ids];
  for(let r=0;r<29;r++){const pairs:Array<[string,string]>=[];for(let i=0;i<15;i++){const a=rotation[i],b=rotation[29-i];pairs.push((r+i)%2===0?[a,b]:[b,a]);}rounds.push(pairs);rotation=[rotation[0],rotation[29],...rotation.slice(1,29)];}
  const games:ScheduledGame[]=[]; const teamGames:Record<string,number>=Object.fromEntries(ids.map(id=>[id,0])); let day=1; let round=0;
  while(Object.values(teamGames).some(n=>n<162)) { for(const [away,home] of rounds[round%rounds.length]) { if(teamGames[away]<162&&teamGames[home]<162){games.push({id:`g-${day}-${away}-${home}`,day,awayId:away,homeId:home});teamGames[away]++;teamGames[home]++;} } day++;round++; }
  return games;
}
