import type {SimPlayer} from './players';
import type {DailyGamePlan} from './gamePlan';
export type Half='TOP'|'BOTTOM';
export type ManagerDecision='HIT_AWAY'|'BUNT'|'STEAL'|'PINCH_HIT'|'CHANGE_PITCHER'|'DEFENSIVE_SUB';
export interface LiveTeamState{teamId:string;lineup:string[];bench:string[];bullpen:string[];pitcherId:string;battingIndex:number;runs:number;hits:number;pitchCount:number;usedPlayers:string[]}
export interface LiveGameState{inning:number;half:Half;outs:number;bases:(string|null)[];away:LiveTeamState;home:LiveTeamState;log:string[];final:boolean}
const pitcher=(p:SimPlayer)=>['P','SP','RP','CP'].includes(p.position);
export function createLiveTeam(teamId:string,players:SimPlayer[],plan:DailyGamePlan):LiveTeamState{const roster=players.filter(p=>p.teamId===teamId&&(p.health??100)>30);const lineup=plan.lineupIds.filter(id=>roster.some(p=>p.id===id));const starter=roster.find(p=>p.id===plan.starterId)??roster.find(p=>pitcher(p));const unavailable=new Set(plan.unavailableRelieverIds);return{teamId,lineup,bench:roster.filter(p=>!pitcher(p)&&!lineup.includes(p.id)).map(p=>p.id),bullpen:roster.filter(p=>['RP','CP'].includes(p.position)&&!unavailable.has(p.id)).map(p=>p.id),pitcherId:starter?.id??'',battingIndex:0,runs:0,hits:0,pitchCount:0,usedPlayers:starter?[starter.id]:[]}}
export function createLiveGame(away:LiveTeamState,home:LiveTeamState):LiveGameState{return{inning:1,half:'TOP',outs:0,bases:[null,null,null],away,home,log:['Play ball.'],final:false}}
export function changePitcher(state:LiveGameState,team:'away'|'home',playerId:string){const club=state[team];if(!club.bullpen.includes(playerId))return state;club.pitcherId=playerId;club.usedPlayers.push(playerId);club.bullpen=club.bullpen.filter(id=>id!==playerId);club.pitchCount=0;return{...state,log:[...state.log,`${playerId} enters from the bullpen.`]}}
export function pinchHit(state:LiveGameState,team:'away'|'home',playerId:string){const club=state[team];if(!club.bench.includes(playerId))return state;const slot=club.battingIndex%9;const replaced=club.lineup[slot];club.lineup[slot]=playerId;club.bench=club.bench.filter(id=>id!==playerId);club.usedPlayers.push(playerId);return{...state,log:[...state.log,`${playerId} pinch hits for ${replaced}.`]}}
export function defensiveSub(state:LiveGameState,team:'away'|'home',outId:string,inId:string){const club=state[team];const slot=club.lineup.indexOf(outId);if(slot<0||!club.bench.includes(inId))return state;club.lineup[slot]=inId;club.bench=club.bench.filter(id=>id!==inId);club.usedPlayers.push(inId);return{...state,log:[...state.log,`${inId} enters defensively for ${outId}.`]}}
export function shouldPromptManager(state:LiveGameState,userTeamId:string,plan:DailyGamePlan){const offense=state.half==='TOP'?state.away:state.home;const defense=state.half==='TOP'?state.home:state.away;const prompts:ManagerDecision[]=[];if(offense.teamId===userTeamId&&state.outs<2&&state.bases[0]){if(plan.steals!=='CONSERVATIVE')prompts.push('STEAL');if(plan.bunts!=='CONSERVATIVE')prompts.push('BUNT')}if(offense.teamId===userTeamId&&offense.bench.length)prompts.push('PINCH_HIT');if(defense.teamId===userTeamId&&defense.bullpen.length&&(defense.pitchCount>=plan.pitchLimit||state.inning>=7))prompts.push('CHANGE_PITCHER');if(defense.teamId===userTeamId&&state.inning>=7&&plan.defenseLate==='AGGRESSIVE'&&defense.bench.length)prompts.push('DEFENSIVE_SUB');return prompts}
export function advanceHalf(state:LiveGameState){if(state.final)return state;if(state.half==='TOP')return{...state,half:'BOTTOM' as Half,outs:0,bases:[null,null,null]};const inning=state.inning+1;if(inning>9&&state.away.runs!==state.home.runs)return{...state,final:true,log:[...state.log,'Final.']};return{...state,inning,half:'TOP' as Half,outs:0,bases:[null,null,null]}}
