import type {SimPlayer} from './players';
export type OfficeActionType='REST'|'ACTIVATE'|'IL'|'CALL_UP'|'OPTION'|'DFA'|'LINEUP'|'MEETING'|'TRADE_INQUIRY'|'UNKNOWN';
export interface OfficeAction{type:OfficeActionType;playerId?:string;playerName?:string;days?:number;targetTeam?:string;raw:string;confidence:number}
export interface CharacterState{playerId:string;loyalty:number;ego:number;leadership:number;competitiveness:number;mediaTolerance:number;relationship:number;morale:number;memories:string[]}
const norm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9 ]/g,' ');
function mentionedPlayer(text:string,players:SimPlayer[]){const n=norm(text);return players.filter(p=>n.includes(norm(p.name))).sort((a,b)=>b.name.length-a.name.length)[0]}
export function interpretOfficeDirection(text:string,teamId:string,players:SimPlayer[]):OfficeAction[]{const roster=players.filter(p=>p.teamId===teamId),p=mentionedPlayer(text,roster),n=norm(text),out:OfficeAction[]=[];const add=(type:OfficeActionType,confidence=.9,extra:Partial<OfficeAction>={})=>out.push({type,playerId:p?.id,playerName:p?.name,raw:text,confidence,...extra});if(/injured list|\bil\b/.test(n))add('IL',.94,{days:Number(n.match(/(10|15|60) day/)?.[1]??10)});if(/activate|bring .* off/.test(n))add('ACTIVATE');if(/call up|promote/.test(n))add('CALL_UP');if(/option|send .* down|triple a/.test(n))add('OPTION');if(/dfa|designate .* assignment/.test(n))add('DFA');if(/rest|day off|sit /.test(n))add('REST');if(/batting order|lineup|bat .* (first|second|third|fourth|fifth|sixth|seventh|eighth|ninth)/.test(n))add('LINEUP',.82);if(/meet|talk to|speak with|reevaluate|check on/.test(n))add('MEETING',.85);if(/trade|call .* about|offer|acquire/.test(n))add('TRADE_INQUIRY',.75);return out.length?out:[{type:'UNKNOWN',raw:text,confidence:.2}]}
function h(s:string){let x=2166136261;for(const c of s)x=Math.imul(x^c.charCodeAt(0),16777619);return x>>>0}const r=(id:string,k:string,lo=25,hi=95)=>lo+h(id+k)%(hi-lo+1);
export function initialCharacter(p:SimPlayer):CharacterState{return{playerId:p.id,loyalty:r(p.id,'loyal'),ego:r(p.id,'ego'),leadership:r(p.id,'lead'),competitiveness:r(p.id,'comp',55,99),mediaTolerance:r(p.id,'media'),relationship:r(p.id,'rel',45,75),morale:r(p.id,'morale',55,85),memories:[]}}
export function reactToAction(state:CharacterState,action:OfficeAction):CharacterState{let morale=state.morale,relationship=state.relationship;const memory=`${action.type}: ${action.raw}`;if(action.type==='REST'){morale+=state.ego>75?-4:2;relationship+=state.relationship>55?1:0}if(action.type==='IL'){morale-=3;relationship+=2}if(action.type==='CALL_UP'){morale+=10;relationship+=5}if(action.type==='OPTION'){morale-=Math.round(state.ego/12);relationship-=4}if(action.type==='DFA'){morale-=15;relationship-=12}if(action.type==='MEETING'){relationship+=4;morale+=2}return{...state,morale:Math.max(0,Math.min(100,morale)),relationship:Math.max(0,Math.min(100,relationship)),memories:[memory,...state.memories].slice(0,20)}}
export function characterDialogue(p:SimPlayer,state:CharacterState,action:OfficeAction){if(action.type==='CALL_UP')return `${p.name}: “I’ve been waiting for this. I’m ready to help us win.”`;if(action.type==='OPTION')return state.ego>70?`${p.name}: “I don’t agree with it, but I heard you.”`:`${p.name}: “I’ll get my work in and be ready when you need me.”`;if(action.type==='REST')return state.competitiveness>80?`${p.name}: “I want to play, but I understand the bigger picture.”`:`${p.name}: “That works. I’ll use the day.”`;if(action.type==='IL')return `${p.name}: “I’ll work with medical and get back as soon as I can.”`;if(action.type==='MEETING')return state.relationship>65?`${p.name}: “I appreciate you coming to me directly.”`:`${p.name}: “Okay. Tell me what you’re thinking.”`;return `${p.name}: “Understood.”`}
