import type {SimPlayer} from './players';
export interface TradeContext{day?:number;otherPlan?:'CONTEND'|'HOLD'|'SELL';needs?:string[];untouchablePlayerIds?:string[];relationship?:number;previousRounds?:number;competition?:number}
export interface TradeTalk{userTeamId:string;otherTeamId:string;targetPlayerId:string;offeredPlayerIds:string[];round:number;status:'OPEN'|'COUNTER'|'ACCEPTED'|'REJECTED';message:string;relationship:number;pressure:number;rumorRisk:number}
const pitcher=(p:SimPlayer)=>['P','SP','RP','CP'].includes(p.position);
export function tradeValue(p:SimPlayer){const skill=pitcher(p)?p.pitching*.45+p.control*.3+p.stamina*.15:p.contact*.25+p.power*.25+p.discipline*.15+p.defense*.15+p.speed*.1;return Math.round(skill+(p.health??100)*.05-(p.fatigue??0)*.03)}
export function findTradeTarget(text:string,userTeamId:string,players:SimPlayer[]){const n=text.toLowerCase();return players.filter(p=>p.teamId!==userTeamId&&n.includes(p.name.toLowerCase())).sort((a,b)=>b.name.length-a.name.length)[0]}
function fitBonus(p:SimPlayer,needs:string[]=[]){if(needs.includes('P')&&pitcher(p))return 10;if(needs.includes('BAT')&&!pitcher(p))return 10;return 0}
export function startTradeTalk(userTeamId:string,target:SimPlayer,players:SimPlayer[],ctx:TradeContext={}):TradeTalk{const relationship=ctx.relationship??50;if(ctx.untouchablePlayerIds?.includes(target.id))return{userTeamId,otherTeamId:target.teamId,targetPlayerId:target.id,offeredPlayerIds:[],round:1,status:'REJECTED',message:`${target.name} is not available. We are not opening that discussion.`,relationship,pressure:0,rumorRisk:5};const assets=players.filter(p=>p.teamId===userTeamId&&(p.health??100)>40).sort((a,b)=>(tradeValue(b)+fitBonus(b,ctx.needs))-(tradeValue(a)+fitBonus(a,ctx.needs)));const multiplier=ctx.otherPlan==='CONTEND'?1.15:ctx.otherPlan==='SELL'?.9:1;const ask=assets.find(p=>tradeValue(p)+fitBonus(p,ctx.needs)>=tradeValue(target)*.8*multiplier);return{userTeamId,otherTeamId:target.teamId,targetPlayerId:target.id,offeredPlayerIds:ask?[ask.id]:[],round:1,status:'COUNTER',relationship,pressure:ctx.competition??0,rumorRisk:12,message:ask?`We will discuss ${target.name}, but ${ask.name} has to be part of the conversation.`:`We will listen on ${target.name}, but this will take a stronger package than what we see right now.`}}
export function respondToTrade(talk:TradeTalk,players:SimPlayer[],userText:string,ctx:TradeContext={}):TradeTalk{const target=players.find(p=>p.id===talk.targetPlayerId);if(!target||target.teamId!==talk.otherTeamId)return{...talk,status:'REJECTED',message:'That player is no longer available.'};const n=userText.toLowerCase();if(/walk away|never mind|cancel|no deal/.test(n))return{...talk,status:'REJECTED',round:talk.round+1,message:'Understood. We are ending the conversation.'};const userRoster=players.filter(p=>p.teamId===talk.userTeamId);const named=userRoster.filter(p=>n.includes(p.name.toLowerCase()));const offers=named.length?named.map(p=>p.id):talk.offeredPlayerIds;const offered=offers.map(id=>players.find(p=>p.id===id&&p.teamId===talk.userTeamId)).filter(Boolean) as SimPlayer[];const offerValue=offered.reduce((s,p)=>s+tradeValue(p)+fitBonus(p,ctx.needs),0);let targetValue=tradeValue(target);if(ctx.otherPlan==='CONTEND')targetValue*=1.15;if(ctx.otherPlan==='SELL')targetValue*=.9;targetValue*=1+Math.min(.15,talk.pressure*.02);targetValue*=1-Math.max(-.08,Math.min(.08,(talk.relationship-50)/500));const accepted=offerValue>=targetValue*.95;const relationship=Math.max(0,Math.min(100,talk.relationship+(accepted?3:offerValue<targetValue*.6?-3:1)));const rumorRisk=Math.min(90,talk.rumorRisk+8+talk.round*3);if(accepted)return{...talk,offeredPlayerIds:offers,round:talk.round+1,status:'ACCEPTED',relationship,rumorRisk,message:`We have a deal for ${target.name}. Send it to the league office.`};const gap=Math.max(1,Math.round(targetValue-offerValue));const competition=talk.pressure>0?' Another club is involved, so we will not hold this open forever.':'';return{...talk,offeredPlayerIds:offers,round:talk.round+1,status:'COUNTER',relationship,rumorRisk,message:`We are still short. Improve the package by roughly ${gap} value points.${competition}`}}
export function negotiationMayLeak(talk:TradeTalk){return talk.rumorRisk>=35}
export function rivalMayWinTarget(talk:TradeTalk){return talk.pressure>=3&&talk.round>=4&&talk.status==='COUNTER'}
