'use client';
import {useEffect,useMemo,useState} from 'react';
import type {SimPlayer} from '../../src/lib/baseball/players';
import {persistedRowsToSimPlayers} from '../../src/lib/baseball/persistentPlayers';
import {coachAlerts,recommendedGamePlan,validateGamePlan,type Aggression,type DailyGamePlan} from '../../src/lib/baseball/gamePlan';
import {listUniverses,loadUniverse} from '../../src/lib/persistence/universe';
const isPitcher=(p:SimPlayer)=>['P','SP','RP','CP'].includes(p.position);
export default function GameDay(){const[saves,setSaves]=useState<any[]>([]),[uid,setUid]=useState(''),[team,setTeam]=useState(''),[date,setDate]=useState(''),[players,setPlayers]=useState<SimPlayer[]>([]),[plan,setPlan]=useState<DailyGamePlan|null>(null),[status,setStatus]=useState('Loading…');useEffect(()=>{listUniverses().then(setSaves)},[]);async function open(id:string){const x=await loadUniverse(id);const ps=persistedRowsToSimPlayers(x.players??[],x.teams??[]);const d=x.universe.game_date;const day=Math.max(1,Math.floor((new Date(d).getTime()-new Date(`${x.universe.current_season}-04-01`).getTime())/86400000)+1);setUid(id);setTeam(x.universe.user_team_key);setDate(d);setPlayers(ps);setPlan(recommendedGamePlan(x.universe.user_team_key,d,day,ps));setStatus('Pregame preparation open. Your choices are for today only.')};const roster=useMemo(()=>players.filter(p=>p.teamId===team),[players,team]);const hitters=roster.filter(p=>!isPitcher(p));const pitchers=roster.filter(isPitcher);function setSlot(i:number,id:string){if(!plan)return;const ids=[...plan.lineupIds];const old=ids.indexOf(id);if(old>=0)[ids[i],ids[old]]=[ids[old],ids[i]];else ids[i]=id;setPlan({...plan,lineupIds:ids})}function setting(k:keyof DailyGamePlan,v:any){plan&&setPlan({...plan,[k]:v})}function toggleRP(id:string){if(!plan)return;const s=new Set(plan.unavailableRelieverIds);s.has(id)?s.delete(id):s.add(id);setPlan({...plan,unavailableRelieverIds:[...s]})}function lock(){if(!plan)return;const e=validateGamePlan(plan,players);if(e.length){setStatus(e.join(' '));return}localStorage.setItem(`gameplan:${uid}:${date}`,JSON.stringify(plan));setStatus('TODAY’S GAME PLAN LOCKED · lineup, starter, bullpen and strategy saved for this game.')}
if(!uid)return <main><header><b>BASEBALL UNIVERSE</b><span>GAME DAY</span></header><section className="paper"><div className="kicker">DAILY MANAGER</div><h2>Choose Your Club</h2>{saves.map(s=><button key={s.id} onClick={()=>open(s.id)}>{s.name} · {s.game_date} →</button>)}<p><a href="/">BACK TO CLUBHOUSE</a></p></section></main>;if(!plan)return null;const alerts=coachAlerts(plan,players);return <main><header><b>BASEBALL UNIVERSE</b><span>GAME DAY · {date}</span></header><section className="paper"><div className="kicker">MANAGER'S OFFICE</div><h1>Set Up Today’s Club</h1><p>{status}</p>{alerts.length>0&&<article><b>BENCH COACH REPORT</b>{alerts.map((a,i)=><p key={i}>{a}</p>)}</article>}<h2>Batting Order</h2>{plan.lineupIds.map((id,i)=>{const p=players.find(x=>x.id===id);return <div key={i}><b>{i+1}.</b> <select value={id} onChange={e=>setSlot(i,e.target.value)}>{hitters.map(h=><option key={h.id} value={h.id}>{h.name} · {h.position} · {h.bats} · FAT {h.fatigue??0} · HLT {h.health??100}</option>)}</select>{p&&<span> Contact {p.contact} · Power {p.power} · Defense {p.defense}</span>}</div>})}<h2>Starting Pitcher</h2><select value={plan.starterId} onChange={e=>setting('starterId',e.target.value)}>{pitchers.filter(p=>['SP','P'].includes(p.position)).map(p=><option key={p.id} value={p.id}>{p.name} · {p.position} · Pitch {p.pitching} · Control {p.control} · FAT {p.fatigue??0}</option>)}</select><label> Pitch limit <input type="number" min="50" max="140" value={plan.pitchLimit} onChange={e=>setting('pitchLimit',Number(e.target.value))}/></label><h2>Bullpen Availability</h2>{pitchers.filter(p=>['RP','CP'].includes(p.position)).map(p=><label key={p.id} style={{display:'block'}}><input type="checkbox" checked={!plan.unavailableRelieverIds.includes(p.id)} onChange={()=>toggleRP(p.id)}/> {p.name} AVAILABLE · FAT {p.fatigue??0} · HLT {p.health??100}</label>)}<h2>Manager Strategy</h2>{(['baserunning','steals','bunts','pinchHit','defenseLate'] as const).map(k=><label key={k} style={{display:'block'}}>{k} <select value={plan[k]} onChange={e=>setting(k,e.target.value as Aggression)}><option>CONSERVATIVE</option><option>NORMAL</option><option>AGGRESSIVE</option></select></label>)}<label><input type="checkbox" checked={plan.platoon} onChange={e=>setting('platoon',e.target.checked)}/> Use platoon advantage</label><h2>Manager Notes</h2><textarea value={plan.notes} onChange={e=>setting('notes',e.target.value)} placeholder="Example: Give the catcher a day off tomorrow. Avoid using the closer unless we have a lead."/><button className="primary huge" onClick={lock}>LOCK TODAY’S GAME PLAN →</button><p><a href="/">BACK TO CLUBHOUSE</a></p></section></main>}
