'use client';
import {useEffect,useMemo,useState} from 'react';
import {CLUBS} from '../../src/lib/baseball/league';
import type {SimPlayer} from '../../src/lib/baseball/players';
import {persistedRowsToSimPlayers} from '../../src/lib/baseball/persistentPlayers';
import {findTradeTarget,respondToTrade,startTradeTalk,type TradeTalk} from '../../src/lib/baseball/tradeTalk';
import {persistUserTrade} from '../../src/lib/persistence/frontOffice';
import {listUniverses,loadUniverse} from '../../src/lib/persistence/universe';

type Msg={who:'YOU'|'GM';text:string};
export default function TradeDesk(){const[saves,setSaves]=useState<any[]>([]),[universeId,setUniverseId]=useState(''),[teamId,setTeamId]=useState(''),[players,setPlayers]=useState<SimPlayer[]>([]),[targetText,setTargetText]=useState(''),[talk,setTalk]=useState<TradeTalk|null>(null),[messages,setMessages]=useState<Msg[]>([]),[reply,setReply]=useState(''),[status,setStatus]=useState('Loading your universes…');
 useEffect(()=>{listUniverses().then(x=>{setSaves(x);setStatus(x.length?'Choose a universe.':'No saved universes found.')}).catch(e=>setStatus(e.message))},[]);
 const target=useMemo(()=>talk?players.find(p=>p.id===talk.targetPlayerId):undefined,[talk,players]);const other=CLUBS.find(c=>c.id===talk?.otherTeamId);const offered=talk?.offeredPlayerIds.map(id=>players.find(p=>p.id===id)).filter(Boolean) as SimPlayer[]|undefined;
 async function openUniverse(id:string){setStatus('Loading trade market…');const x=await loadUniverse(id);const real=persistedRowsToSimPlayers(x.players??[],x.teams??[]);setUniverseId(id);setTeamId(x.universe.user_team_key);setPlayers(real);setTalk(null);setMessages([]);setStatus(`${real.length} players loaded. Type the real player you want to acquire.`)}
 function openTalk(){const p=findTradeTarget(targetText,teamId,players);if(!p){setStatus('I could not find that player on another club. Type the player’s full name.');return}const t=startTradeTalk(teamId,p,players);setTalk(t);setMessages([{who:'YOU',text:`I want to discuss ${p.name}.`},{who:'GM',text:t.message}]);setReply('');setStatus(`Negotiating with ${CLUBS.find(c=>c.id===p.teamId)?.name??p.teamId}.`)}
 function send(){if(!talk||!reply.trim())return;const next=respondToTrade(talk,players,reply);setMessages(m=>[...m,{who:'YOU',text:reply},{who:'GM',text:next.message}]);setTalk(next);setReply('');setStatus(next.status==='ACCEPTED'?'Terms agreed. Finalize the trade to move the players.':next.status==='REJECTED'?'Negotiation ended.':'Counteroffer received.')}
 async function finalize(){if(!talk||talk.status!=='ACCEPTED'||!universeId)return;setStatus('Finalizing transaction…');try{const done=await persistUserTrade(universeId,talk);const x=await loadUniverse(universeId);setPlayers(persistedRowsToSimPlayers(x.players??[],x.teams??[]));setMessages(m=>[...m,{who:'GM',text:'The transaction is official. We will notify the players and the league office.'}]);setStatus(`TRADE COMPLETE · Acquired ${done.targetName} · Sent ${done.offeredNames.join(', ')||'agreed return'}`)}catch(e:any){setStatus(`Trade could not be finalized: ${e.message}`)}}
 if(!universeId)return <main><header><b>BASEBALL UNIVERSE</b><span>TRADE DESK</span></header><section className="paper"><div className="kicker">FRONT OFFICE</div><h2>Choose a Universe</h2>{saves.map(s=><button key={s.id} onClick={()=>openUniverse(s.id)}>{s.name} · {s.game_date} →</button>)}<p>{status}</p><a href="/">BACK TO CLUBHOUSE</a></section></main>;
 if(!talk)return <main><header><b>BASEBALL UNIVERSE</b><span>TRADE DESK</span></header><section className="paper"><div className="kicker">PLAYER ACQUISITION</div><h2>Call Another GM</h2><p>Type the full name of a real player in your universe. Their club will open negotiations based on the current rosters and player values.</p><input value={targetText} onChange={e=>setTargetText(e.target.value)} placeholder="Player name"/><button className="primary" onClick={openTalk}>CALL CLUB →</button><p>{status}</p><a href="/">BACK TO CLUBHOUSE</a></section></main>;
 return <main><header><b>BASEBALL UNIVERSE</b><span>TRADE DESK · ROUND {talk.round}</span></header><section className="paper"><div className="kicker">LIVE NEGOTIATION</div><h2>{other?.city} {other?.name}</h2><p><b>Target:</b> {target?.name} · {target?.position}</p><p><b>Current package:</b> {offered?.length?offered.map(p=>p?.name).join(', '):'No players named yet'}</p><article>{messages.map((m,i)=><p key={i}><b>{m.who==='YOU'?'YOU':`${other?.abbr??'OTHER'} GM`}:</b> {m.text}</p>)}</article>{talk.status==='COUNTER'||talk.status==='OPEN'?<><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Example: I’ll give you Player A and Player B. Or: walk away."/><button className="primary" onClick={send}>SEND OFFER →</button></>:null}{talk.status==='ACCEPTED'&&<button className="primary huge" onClick={finalize}>FINALIZE TRADE →</button>}<p><b>{status}</b></p><button onClick={()=>{setTalk(null);setMessages([]);setTargetText('')}}>NEW TRADE CALL</button><a href="/">BACK TO CLUBHOUSE</a></section></main>}
