'use client';
import {useEffect,useMemo,useState} from 'react';
import {CLUBS} from '../../src/lib/baseball/league';
import type {SimPlayer} from '../../src/lib/baseball/players';
import {persistedRowsToSimPlayers} from '../../src/lib/baseball/persistentPlayers';
import {buildRivalReturnPackage} from '../../src/lib/baseball/rivalTrade';
import {findTradeTarget,negotiationMayLeak,respondToTrade,rivalMayWinTarget,startTradeTalk,type TradeTalk} from '../../src/lib/baseball/tradeTalk';
import {persistTrade,persistTradeRumor,persistUserTrade} from '../../src/lib/persistence/frontOffice';
import {listUniverses,loadUniverse} from '../../src/lib/persistence/universe';
type Msg={who:'YOU'|'GM'|'REPORTER';text:string};
export default function TradeDesk(){const[saves,setSaves]=useState<any[]>([]),[universeId,setUniverseId]=useState(''),[teamId,setTeamId]=useState(''),[players,setPlayers]=useState<SimPlayer[]>([]),[teams,setTeams]=useState<any[]>([]),[memories,setMemories]=useState<any[]>([]),[targetText,setTargetText]=useState(''),[talk,setTalk]=useState<TradeTalk|null>(null),[messages,setMessages]=useState<Msg[]>([]),[reply,setReply]=useState(''),[status,setStatus]=useState('Loading your universes…'),[rumorSaved,setRumorSaved]=useState(false);useEffect(()=>{listUniverses().then(x=>{setSaves(x);setStatus(x.length?'Choose a universe.':'No saved universes found.')}).catch(e=>setStatus(e.message))},[]);const target=useMemo(()=>talk?players.find(p=>p.id===talk.targetPlayerId):undefined,[talk,players]);const other=CLUBS.find(c=>c.id===talk?.otherTeamId);const offered=talk?.offeredPlayerIds.map(id=>players.find(p=>p.id===id)).filter(Boolean) as SimPlayer[]|undefined;
async function openUniverse(id:string){setStatus('Loading trade market…');const x=await loadUniverse(id);const real=persistedRowsToSimPlayers(x.players??[],x.teams??[]);setUniverseId(id);setTeamId(x.universe.user_team_key);setPlayers(real);setTeams(x.teams??[]);setMemories(x.memories??[]);setTalk(null);setMessages([]);setRumorSaved(false);setStatus(`${real.length} players loaded. Type the real player you want to acquire.`)}
function contextFor(otherTeamId:string,targetId?:string){const t=teams.find((x:any)=>x.team_key===otherTeamId);const strategy=t?.strategy??{};const history=memories.filter((m:any)=>m.subject_type==='TEAM'&&m.subject_id===t?.id);return{otherPlan:strategy.competitiveWindow??'HOLD',needs:strategy.positionalNeeds??[],untouchablePlayerIds:strategy.untouchablePlayerIds??[],relationship:Math.max(25,50-history.filter((m:any)=>m.sentiment<0).length*3+history.filter((m:any)=>m.sentiment>0).length*2),previousRounds:history.length,competition:targetId?Math.min(5,Math.floor((targetId.charCodeAt(0)+targetId.length)%6)):0} as any}
function openTalk(){const p=findTradeTarget(targetText,teamId,players);if(!p){setStatus('I could not find that player on another club. Type the player’s full name.');return}const t=startTradeTalk(teamId,p,players,contextFor(p.teamId,p.id));setTalk(t);setMessages([{who:'YOU',text:`I want to discuss ${p.name}.`},{who:'GM',text:t.message}]);setReply('');setRumorSaved(false);setStatus(t.status==='REJECTED'?'That club considers the player untouchable.':`Negotiating with ${CLUBS.find(c=>c.id===p.teamId)?.name??p.teamId}.`)}
async function completeRivalDeal(next:TradeTalk){if(!universeId||!target)return null;const possible=CLUBS.filter(c=>c.id!==teamId&&c.id!==next.otherTeamId);if(!possible.length)return null;const rival=possible[(next.targetPlayerId.length+next.round)%possible.length];const rivalRoster=players.filter(p=>p.teamId===rival.id);const pkg=buildRivalReturnPackage(target,rivalRoster);const asset=pkg[0];if(!asset)return null;await persistTrade(universeId,{fromTeamId:rival.id,toTeamId:next.otherTeamId,offeredPlayerId:asset.id,requestedPlayerId:target.id,score:80,reason:'Rival club won a competitive trade negotiation'});return{teamKey:rival.id,returnNames:[asset.name]}}
async function send(){if(!talk||!reply.trim())return;const next=respondToTrade(talk,players,reply,contextFor(talk.otherTeamId,talk.targetPlayerId));let extra:Msg[]=[];const leak=negotiationMayLeak(next)&&!messages.some(m=>m.who==='REPORTER');if(leak){extra.push({who:'REPORTER',text:`League sources say ${other?.name??'the club'} and your front office have discussed ${target?.name}. The talks are now circulating around the league.`});if(universeId&&target&&!rumorSaved){try{await persistTradeRumor(universeId,next,target.name);setRumorSaved(true)}catch{}}}if(rivalMayWinTarget(next)&&universeId&&target){try{const rival=await completeRivalDeal(next);if(rival){const club=CLUBS.find(c=>c.id===rival.teamKey);extra.push({who:'REPORTER',text:`BREAKING: ${club?.city??rival.teamKey} ${club?.name??''} have acquired ${target.name} for ${rival.returnNames.join(', ')}. Your negotiations are over.`});next.status='REJECTED';next.message=`${target.name} has been traded elsewhere.`;const x=await loadUniverse(universeId);setPlayers(persistedRowsToSimPlayers(x.players??[],x.teams??[]));setMemories(x.memories??[])}}catch(e:any){extra.push({who:'REPORTER',text:`A rival bid developed, but the transaction was not completed: ${e.message}`})}}else if(rivalMayWinTarget(next)){extra.push({who:'GM',text:`We need an answer soon. Another club has made a serious offer for ${target?.name}.`});next.pressure+=1}setMessages(m=>[...m,{who:'YOU',text:reply},{who:'GM',text:next.message},...extra]);setTalk({...next});setReply('');setStatus(next.status==='ACCEPTED'?'Terms agreed. Finalize the trade to move the players.':next.status==='REJECTED'?'Negotiation ended.':'Counteroffer received.')}
async function finalize(){if(!talk||talk.status!=='ACCEPTED'||!universeId)return;setStatus('Finalizing transaction…');try{const done=await persistUserTrade(universeId,talk);const x=await loadUniverse(universeId);setPlayers(persistedRowsToSimPlayers(x.players??[],x.teams??[]));setMemories(x.memories??[]);setMessages(m=>[...m,{who:'GM',text:'The transaction is official. We will notify the players and the league office.'},{who:'REPORTER',text:`BREAKING: Your club has acquired ${done.targetName}.`}]);setStatus(`TRADE COMPLETE · Acquired ${done.targetName} · Sent ${done.offeredNames.join(', ')||'agreed return'}`)}catch(e:any){setStatus(`Trade could not be finalized: ${e.message}`)}}
if(!universeId)return <main><header><b>BASEBALL UNIVERSE</b><span>TRADE DESK</span></header><section className="paper"><div className="kicker">FRONT OFFICE</div><h2>Choose a Universe</h2>{saves.map(s=><button key={s.id} onClick={()=>openUniverse(s.id)}>{s.name} · {s.game_date} →</button>)}<p>{status}</p><a href="/">BACK TO CLUBHOUSE</a></section></main>;
if(!talk)return <main><header><b>BASEBALL UNIVERSE</b><span>TRADE DESK</span></header><section className="paper"><div className="kicker">PLAYER ACQUISITION</div><h2>Call Another GM</h2><p>Type the full name of a real player. Negotiations can leak into the baseball world, affect player memory, and be lost to rival clubs.</p><input value={targetText} onChange={e=>setTargetText(e.target.value)} placeholder="Player name"/><button className="primary" onClick={openTalk}>CALL CLUB →</button><p>{status}</p><a href="/">BACK TO CLUBHOUSE</a></section></main>;
return <main><header><b>BASEBALL UNIVERSE</b><span>TRADE DESK · ROUND {talk.round}</span></header><section className="paper"><div className="kicker">LIVE NEGOTIATION</div><h2>{other?.city} {other?.name}</h2><p><b>Target:</b> {target?.name} · {target?.position}</p><p><b>Current package:</b> {offered?.length?offered.map(p=>p?.name).join(', '):'No players named yet'}</p><p className="small">GM relationship: {talk.relationship}/100 · Rival pressure: {talk.pressure}/5 · Leak risk: {talk.rumorRisk}%</p><article>{messages.map((m,i)=><p key={i}><b>{m.who==='YOU'?'YOU':m.who==='REPORTER'?'REPORTER':`${other?.abbr??'OTHER'} GM`}:</b> {m.text}</p>)}</article>{talk.status==='COUNTER'||talk.status==='OPEN'?<><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Name one or several players in your package, improve the offer, or type walk away."/><button className="primary" onClick={send}>SEND OFFER →</button></>:null}{talk.status==='ACCEPTED'&&<button className="primary huge" onClick={finalize}>FINALIZE TRADE →</button>}<p><b>{status}</b></p><button onClick={()=>{setTalk(null);setMessages([]);setTargetText('');setRumorSaved(false)}}>NEW TRADE CALL</button><a href="/">BACK TO CLUBHOUSE</a></section></main>}
