export const MLB_API='https://statsapi.mlb.com/api/v1';
export type RealMLBPlayer={mlbId:number;name:string;teamId:number;position:string;bats:string;throws:string;age:number;ratings:{contact:number;power:number;discipline:number;speed:number;pitching:number;control:number;stamina:number};source:any};
const clamp=(n:number,min=20,max=99)=>Math.max(min,Math.min(max,Math.round(n)));
async function json(url:string){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`MLB data request failed: ${r.status}`);return r.json()}
export async function fetchMLBTeams(season=2026){const d=await json(`${MLB_API}/teams?sportId=1&season=${season}`);return d.teams??[]}
export async function fetchTeamRoster(teamId:number,season=2026){const d=await json(`${MLB_API}/teams/${teamId}/roster?rosterType=40Man&season=${season}&hydrate=person(stats(group=[hitting,pitching],type=[season],season=${season}))`);return d.roster??[]}
function hittingRatings(stats:any){const s=stats?.find((x:any)=>x.group?.displayName==='hitting')?.splits?.[0]?.stat??{};const avg=Number(s.avg||.240),obp=Number(s.obp||.310),slg=Number(s.slg||.390),hr=Number(s.homeRuns||0),sb=Number(s.stolenBases||0);return{contact:clamp(45+(avg-.240)*180),power:clamp(40+(slg-.390)*100+Math.min(20,hr*.6)),discipline:clamp(45+(obp-.310)*150),speed:clamp(45+Math.min(35,sb*1.4))}}
function pitchingRatings(stats:any){const s=stats?.find((x:any)=>x.group?.displayName==='pitching')?.splits?.[0]?.stat??{};const era=Number(s.era||4.5),whip=Number(s.whip||1.35),k9=Number(s.strikeoutsPer9Inn||8),bb9=Number(s.walksPer9Inn||3.2),ip=Number(s.inningsPitched||0);return{pitching:clamp(68+(4.2-era)*7+(k9-8)*2),control:clamp(68+(3.2-bb9)*5+(1.35-whip)*18),stamina:clamp(35+Math.min(55,ip/2))}}
export function normalizeRosterEntry(entry:any,teamId:number):RealMLBPlayer{const p=entry.person??{},stats=p.stats??[];return{mlbId:p.id,name:p.fullName,teamId,position:entry.position?.abbreviation||p.primaryPosition?.abbreviation||'UT',bats:p.batSide?.code||'R',throws:p.pitchHand?.code||'R',age:p.currentAge||25,ratings:{...hittingRatings(stats),...pitchingRatings(stats)},source:{mlbId:p.id,fullName:p.fullName,position:entry.position,stats}}}
export async function fetchRealLeagueSnapshot(season=2026){const teams=await fetchMLBTeams(season);const rosters=await Promise.all(teams.map(async(t:any)=>({team:t,roster:(await fetchTeamRoster(t.id,season)).map((x:any)=>normalizeRosterEntry(x,t.id))})));return{season,capturedAt:new Date().toISOString(),teams:rosters}}
